### ISSUE TITLE
Missing require causes 'Error: Could not set 'file' on ensure'

### ISSUE THREAD

**Issue by sbocconi** [mlambrichs/puppet-neo4j#1]
Full error:
Error: Could not set 'file' on ensure: No such file or directory @ dir_s_rmdir - /opt/neo4j/neo4j-community-2.1.2/conf/neo4j.properties20160302-6078-1d7bi8q.lock at 169:/tmp/vagrant-puppet/modules-2335a5ee24a96f1f83cf55d58c832f28/concat/manifests/init.pp

In file manifest/init.pp the dependency on the untar is missing:

```
concat{ $properties_file :
    owner  => 'neo4j',
    group  => 'neo4j',
    mode   => '0644',
    >>require => Exec["untar ${package_tarball}"],<<
    before => Service['neo4j'],
    notify => Service['neo4j']
  }
```

**Comment by marclambrichs** [comment]
This should not be a problem anymore. Pushed a complete rewrite just now.
