### ISSUE TITLE
Using 3.0.1 prevents neo4j.service from starting

### ISSUE THREAD

**Issue by DavidRoca** [mlambrichs/puppet-neo4j#2]
The server worked fine with the version 2.1.2

When I tried to update the server with $version = '2.1.2' it fails when it tries to start the service

`Error: Could not start Service[neo4j]: Execution of '/bin/systemctl start neo4j' returned 1: Job for neo4j.service failed. See 'systemctl status neo4j.service' and 'journalctl -xn' for details.
Error: /Stage[main]/Neo4j/Service[neo4j]/ensure: change from stopped to running failed: Could not start Service[neo4j]: Execution of '/bin/systemctl start neo4j' returned 1: Job for neo4j.service failed. See 'systemctl status neo4j.service' and 'journalctl -xn' for details.
`
and then, using 'systemctl status neo4j.service'

`● neo4j.service - (null)
   Loaded: loaded (/etc/init.d/neo4j)
   Active: failed (Result: exit-code) since Thu 2016-06-02 01:09:27 CEST; 1min 29s ago
  Process: 27319 ExecStart=/etc/init.d/neo4j start (code=exited, status=1/FAILURE)

Jun 02 01:09:27 kp2 neo4j[27319]: /etc/init.d/neo4j: line 32: /etc/init.d/neo4j-shared.sh: No such file or directory
Jun 02 01:09:27 kp2 systemd[1]: neo4j.service: control process exited, code=exited status=1
Jun 02 01:09:27 kp2 systemd[1]: Failed to start (null).
Jun 02 01:09:27 kp2 systemd[1]: Unit neo4j.service entered failed state.
`
Thank you in advance

**Comment by marclambrichs** [comment]
Hi David,

Missed this one totally! I apologize. Will have a look at this later today.

Best,
Marc

**Comment by andrewkvavlewhite** [comment]
Anything more on this? I'm having the same issue.

**Comment by marclambrichs** [comment]
Yup. New version pushed, so you can check neo4j 3.x now. Let me know if you still have problems.

**Comment by marclambrichs** [comment]
Closing this. Reopen pls. if according to you problem still exists.
