### ISSUE TITLE
missing directories setting in neo4j.conf

### ISSUE THREAD

**Issue by attachmentgenie** [mlambrichs/puppet-neo4j#20]
The config provided by the official packages have directories setting section which we dont provide.
However dbms.directories.logs and dbms.directories.run are required to get the service to run.

```
# Directory settings.
dbms.directories.logs=/var/log/neo4j
dbms.directories.run=/var/run/neo4j
dbms.directories.lib=/usr/share/neo4j/lib
dbms.directories.certificates=/var/lib/neo4j/certificates
```

**Comment by marclambrichs** [comment]
Merged issue20 branch.
