### ISSUE TITLE
install_java only works on centos

### ISSUE THREAD

**Issue by attachmentgenie** [mlambrichs/puppet-neo4j#9]
```
  if ( $install_java ) {
    class { '::java':
      distribution => 'jdk',
      package      => 'java-1.8.0-openjdk'
    }
  }
```
 only results in a successful install on centos{6,7}

**Comment by attachmentgenie** [comment]
neo4j 3.x requires java 8. which is only available for centos-x and ubuntu-1604. The other os-es require additional repos configures. 

So we either need to extend this feature extensively or remove it entirely

**Comment by attachmentgenie** [comment]
working code for the current supported matrix can be found in 

[examples/init.pp](https://github.com/mlambrichs/puppet-neo4j/blob/master/examples/init.pp)

**Comment by marclambrichs** [comment]
We're going to remove it entirely. Shouldn't be part of a neo4j module, but handled in a puppet profile.
